still trying to capture tf change code=2

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -53,13 +53,17 @@ jobs:
         
         - name: Save plan
           id: plan
-          run: |
-            set +e  
+          run: | 
             terraform plan -detailed-exitcode -out=tfplan
-            echo "exitcode=$?" >> $GITHUB_OUTPUT
-            exit 0
+            EXIT_CODE=$?
+
+            echo "exitcode=EXIT_CODE" >> $GITHUB_OUTPUT
+
+            if [ $EXIT_CODE -eq 1 ]; then
+              echo "Terraform plan failed"
+              exit 1
+            fi
           working-directory: ./terraform
-          continue-on-error: true
 
         - name: Debug exit code
           run: echo "Exit code was ${{ steps.plan.outputs.exitcode }}"
